apiVersion: v1
kind: Service
metadata:
  name: dhr-admin
  namespace: test
spec:
  ports:
    - name: http
      port: 80
      targetPort: 9797
      protocol: TCP
  type: NodePort
  selector:
    app: dhr-admin
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dhr-admin
  namespace: test
  labels:
    app: dhr-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dhr-admin
  template:
    metadata:
      labels:
        app: dhr-admin
    spec:
      containers:
      - image: registry.gitlab.com/kirill.belokon.1991/dhr-admin:master-<VERSION>
        name: dhr
        ports:
        - containerPort:  9797
      imagePullSecrets:
      - name: gitlab
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dhr-admin
  namespace: test
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  tls:
  - hosts:
    - dashboard.dhr.cloud
    secretName: example-com-tls-prod
  rules:
  - host: dashboard.dhr.cloud
    http:
       paths:
       - path: /?(.*)
         backend:
           serviceName: dhr-admin
           servicePort: 80
